networks:
  znuny-net:
    driver: bridge

volumes:
  ZnunyDownload:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ZNUNY_PERSISTENT_FOLDER}/download
  ZnunyPersistent:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ZNUNY_PERSISTENT_FOLDER}/${ZNUNY_INSTANCE}/persistent
  ZnunyLog:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ZNUNY_PERSISTENT_FOLDER}/${ZNUNY_INSTANCE}/log
  ZnunyArticle:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ZNUNY_PERSISTENT_FOLDER}/${ZNUNY_INSTANCE}/article
  ZnunyHTDocs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ZNUNY_PERSISTENT_FOLDER}/${ZNUNY_INSTANCE}/htdocs_custom

services:
  znuny-daemon:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.znuny
      target: daemon
    container_name: znuny_daemon_${ZNUNY_INSTANCE}
    depends_on:
      - znuny-httpd
    networks:
      - znuny-net
    environment:
      DB_HOST: ${DB_HOST:-127.0.0.1}
      DB_NAME: ${DB_NAME:-znuny}
      DB_USER: ${DB_USER:-znuny}
      DB_USER_PASS: ${DB_USER_PASS:-some-pass}
    restart: unless-stopped
    volumes:
      - ZnunyLog:/opt/znuny/var/log
      - ZnunyArticle:/opt/znuny/var/article
      - ZnunyHTDocs:/opt/znuny/var/httpd/htdocs/custom
      - ZnunyPersistent:/persistent

  znuny-httpd:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.znuny
      target: httpd
    container_name: znuny_httpd_${ZNUNY_INSTANCE}
    ports:
      - "${external_port:-80}:80"
    networks:
      - znuny-net
    restart: unless-stopped
    volumes:
      - ZnunyLog:/opt/znuny/var/log
      - ZnunyArticle:/opt/znuny/var/article
      - ZnunyHTDocs:/opt/znuny/var/httpd/htdocs/custom
      - ZnunyPersistent:/persistent
      - ZnunyDownload:/download