volumes:
  MariaDBVol:

services:
  znuny-daemon:
    depends_on:
      - znuny-db

  znuny-httpd:
    depends_on:
      - znuny-db

  znuny-db:
    image: mariadb:${MARIADB_VERSION:-11.4.7}
    container_name: znuny_db
    mem_limit: ${ZNUNY_DB_MEMLIMIT:-2048m}
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS:-root-pass}
      MYSQL_DATABASE: ${DB_NAME:-znuny}
      MYSQL_USER: ${DB_USER:-znuny}
      MYSQL_PASSWORD: ${DB_USER_PASS:-some-pass}
    volumes:
      - MariaDBVol:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - znuny-net
    command: [
      "--max_allowed_packet=256M",
      "--innodb_log_file_size=512M"
    ]
    labels:
      org.label-schema.group: "znuny"